---
title: "Species Template"
format: html
embed-resources: true 
---

```{r Packages}
library(tidyverse)
library(scico)
source("2_Model/Code/Run_SDP.R")
```

## Set parameters

```{r SetParameters}
# Species name
species_name <- "Swift Parrot"

# Fecundity in wild and in captivity
fecundity_w <- 1.54
fecundity_c <- 1

# Month of breeding
breeding_month <- 8

# Monthly mortality in wild without H5N1, with H5N1, and in captivity
mortality_w_base <- 0.04
mortality_w_flu <- 0.5
mortality_c <- 0.03

# Translocation success rates (wild to captive, captive to wild)
phi_wc <- 0.9
phi_cw <- 0.75

# Disease transition matrix: Rows are exposure at t, columns at t+1
disease_transitions <- matrix(
  #   1      2      3      4      5      6
  c(0.990, 0.009, 0.001, 0.000, 0.000, 0.000, # 1
    0.100, 0.500, 0.250, 0.100, 0.050, 0.000, # 2 
    0.050, 0.050, 0.500, 0.250, 0.150, 0.050, # 3
    0.050, 0.050, 0.050, 0.500, 0.250, 0.100, # 4
    0.050, 0.000, 0.000, 0.000, 0.250, 0.700, # 5
    0.600, 0.000, 0.000, 0.000, 0.000, 0.400),# 6
  nrow = 6, 
  ncol = 6, 
  byrow = TRUE)

# Preview transition matrix
disease_transitions |>
  as.data.frame() |>
  mutate(t = as.character(1:6)) |>
  pivot_longer(cols = paste0("V",1:6), 
               names_to = "tp1", 
               values_to = "prob") |>
  mutate(tp1 = str_remove(tp1, "V")) |>
  ggplot(aes(y = t, x = tp1, fill = prob, label = prob)) +
  geom_tile() +
  geom_text(colour = "white") +
  labs(y = "t", x = "t+1") +
  theme(legend.position = "bottom")
  
```

## Run SDP

```{r RunSDP}
sdp_output <- run_SDP(fecundity_w = fecundity_w,
                      fecundity_c = fecundity_c, 
                      breeding_month = breeding_month, 
                      mortality_w_base = mortality_w_base,
                      mortality_w_flu = mortality_w_flu,
                      mortality_c = mortality_c, 
                      phi_wc = phi_wc,
                      phi_cw = phi_cw, 
                      disease_transitions = disease_transitions,
                      discount = 0.99,
                      Tmax = 360)



```

## Save outputs

```{r SaveOutputs}
write_rds(paste0("2_Model/Outputs/Species/", species_name, ".rds"),
          sdp_output)
```
