---
title: "SWPA_SDP"
format: html
---

```{r Packages}
library(tidyverse)
library(scico)
```

## Step 1: Define objectives

Preserve population, maximise wild population.

## Step 2: Define states

```{r 2_DefineStates}

## Sub-state axes
# Wild pop: 0-2000, increments of 100
Nstates_nWild <- 21
states_nWild <- 1:21

# Captive pop: 0-2000, increments of 100
Nstates_nCaptive <- 21
states_nCaptive <- 1:21

# Infected: binary
Nstates_infected <- 2
states_infected <- c(FALSE, TRUE)

# Infected: Exposure
Nstates_exposure <- 6
states_exposure <- 1:6

# Breeding: Binary
Nstates_breeding <- 2
states_breeding <- c(FALSE, TRUE)

# Month: 1:12
Nstates_month <- 12
states_month <- 1:12

# Number of states (only population) 
nStates_pop <- Nstates_nWild*Nstates_nCaptive

# Total number of states
nStates_full <- Nstates_nWild*Nstates_nCaptive*Nstates_exposure*Nstates_month
```

## Step 3: Define control actions

```{r 3_DefineControls}
actions <- seq(-100, 100, by = 10)

# Total number of actions
nActions <- length(actions)
```

## Step 4: Define dynamic model

```{r 4_DefineDynamicModel}

# Fecundity rate
fecundity_w <- 3.29*.9*.52
fecundity_c <- 1

# Mortality rate
mortality_w_base <- 45/12/100
mortality_w_flu <- 0.30
mortality_c <- 30/12/100

# Breeding indicator
breeding <- 1
breeding_month <- 8

# Translocation success rates
phi_wc <- 0.9
phi_cw <- 0.75

#### This function should predict the next population of the wild and captive 
#### population given an action, *deterministically*. The stochastic aspects,
#### ie whether the pop ends up diseased next stage and how its exposure changes,
#### 
dynamic <- function(actualWild, actualCaptive, action,
                    disease, mortality_w_base, 
                    mortality_w_flu, mortality_c, 
                    breeding, fecundity_w, fecundity_c, 
                    phi_wc, phi_cw){
  
  tau_cw <- ifelse(action > 0, action, 0)/100
  tau_wc <- ifelse(action < 0, abs(action), 0)/100
  mortality_w <- ifelse(disease == 1, mortality_w_flu, mortality_w_base)
  
  nextWild <- 
    ((actualWild-(actualWild*tau_wc))*(1-mortality_w)) + 
    ((actualWild-(actualWild*tau_wc))*breeding*fecundity_w) +
    (actualCaptive*tau_cw*phi_cw*(1-mortality_c))
  
  nextCaptive <- 
    ((actualCaptive-(actualCaptive*tau_cw))*(1-mortality_c)) + 
    ((actualCaptive-(actualCaptive*tau_cw))*breeding*fecundity_c) +
    (actualWild*tau_wc*phi_wc*(1-mortality_w))
  
	nextpop <- list(Wild = nextWild,
	                Captive = nextCaptive)
	  
	return(nextpop)
}
```

## Step 5: Define utility function

Wild individuals twice as valuable as captive ones

```{r 5_DefineUtility}
get_utility <- function(wildPop, captivePop) {
  utility <- ((wildPop-1)*2)+((captivePop-1))
}
```

## Step 6: Solve Bellman via value iteration

```{r 6_SolveBellman}

# Population transitions
transitions_pop <- array(0, 
                        dim = c(Nstates_nWild,
                                Nstates_nCaptive,
                                Nstates_nWild,
                                Nstates_nCaptive,
                                2, # disease
                                2, # breeding
                                nActions))

# Infection transitions 
transitions_disease <- array(0,
                             dim = c(6, 6))

# Utility matrix
utility <- array(0, 
                 dim = c(Nstates_nWild,
                         Nstates_nCaptive,
                         Nstates_exposure,
                         Nstates_month,
                         nActions))


# Iterate over possible states
for (w in 1:Nstates_nWild){
  for (x in 1:Nstates_nCaptive){
    for (y in 1:Nstates_infected){
      for (z in 1:Nstates_breeding){
        # And possible actions
        for (i in 1:nActions){
          
          # Calculate next population given the state & action
          nextpop <- dynamic(actualWild = states_nWild[w]-1, 
                             actualCaptive = states_nCaptive[x]-1,
                             disease = states_infected[y],
                             action = actions[i],
                             mortality_w_base = mortality_w_base, 
                             mortality_w_flu = mortality_w_flu, 
                             mortality_c = mortality_c, 
                             breeding = states_breeding[z], 
                             fecundity_w = fecundity_w, 
                             fecundity_c = fecundity_c, 
                             phi_wc = phi_wc, 
                             phi_cw = phi_cw)
          
          # Round into states
          nextWildState <- round(nextpop$Wild)+1
          nextWildState <- ifelse(nextWildState>21, 21, nextWildState)
          nextCaptiveState <- round(nextpop$Captive)+1
          nextCaptiveState <- ifelse(nextCaptiveState>21, 21, nextCaptiveState)
          
          # Add to matrix
          transitions_pop[w, x, nextWildState, nextCaptiveState, y, z, i] <- 1

		      # Compute utility
          if (y == 1 & z == 1){
            utility[w, x, 1:5, c(1:7, 9:12), i] <- get_utility(nextWildState,
                                                               nextCaptiveState)
          }
          if (y == 1 & z == 2){
            utility[w, x, 1:5, 8, i] <- get_utility(nextWildState,
                                                    nextCaptiveState)
          }
          if (y == 2 & z == 1){
            utility[w, x, 6, c(1:7, 9:12), i] <- get_utility(nextWildState,
                                                             nextCaptiveState)
          }
          if (y == 2 & z == 2){
            utility[w, x, 6, 8, i] <- get_utility(nextWildState,
                                                  nextCaptiveState)
          }
        }
      }
    }
  }
}

# Fill in disease transitions
transitions_disease[1, 1] <- .99
transitions_disease[1, 2] <- .009
transitions_disease[1, 3] <- .001
transitions_disease[2, 1] <- .1
transitions_disease[2, 2] <- .5
transitions_disease[2, 3] <- .25
transitions_disease[2, 4] <- .1
transitions_disease[2, 5] <- .05
transitions_disease[3, 1] <- .05
transitions_disease[3, 2] <- .05
transitions_disease[3, 3] <- .5
transitions_disease[3, 4] <- .25
transitions_disease[3, 5] <- .15
transitions_disease[3, 6] <- .05
transitions_disease[4, 1] <- .05
transitions_disease[4, 2] <- .05
transitions_disease[4, 3] <- .05
transitions_disease[4, 4] <- .5
transitions_disease[4, 5] <- .25
transitions_disease[4, 6] <- .10
transitions_disease[5, 1] <- .05
transitions_disease[5, 2] <- 0
transitions_disease[5, 3] <- 0
transitions_disease[5, 4] <- 0
transitions_disease[5, 5] <- .25
transitions_disease[5, 6] <- .7
transitions_disease[6, 1] <- .6
transitions_disease[6, 6] <- .4

# Discount factor
discount <- 0.99

# Time horizon
Tmax <- 12*30
#Tmax <- 10
Tmonths <- rep_len(c(8:12,1:7),length.out = Tmax)

## Calculate value of each state at TMax
Vtmax <- array(0,
               dim = c(Nstates_nWild, 
                       Nstates_nCaptive, 
                       Nstates_exposure, 
                       Nstates_month))

for (i in 1:Nstates_nWild){
  for (j in 1:Nstates_nCaptive){
    Vtmax[i,j,,] <- get_utility(states_nWild[i], states_nCaptive[j])
  }
}


# Action value array at t and t+1
Vt <-  array(0,
             dim = c(Nstates_nWild, Nstates_nCaptive, 
                     Nstates_exposure, Nstates_month))
Vtplus <-  Vtmax 

# Optimal policy array
D <- array(0,
           dim = c(Nstates_nWild, Nstates_nCaptive, 
                   Nstates_exposure, Nstates_month))


for (t in (Tmax-1):1){

# We define an array Q that stores the updated action values for all states and actions
  
  Q <- array(0, 
             dim = c(Nstates_nWild,
                     Nstates_nCaptive,
                     Nstates_exposure,
                     Nstates_month,
                     nActions))
  W <-  array(0, 
              dim = c(Nstates_nWild,
                      Nstates_nCaptive,
                      Nstates_exposure))

  
	for (i in 1:length(actions)) {
	  for (w in 1:Nstates_nWild){
	    for (x in 1:Nstates_nCaptive){
	      for (y in 1:Nstates_exposure){
	        # Prob of next state
	        for (z in 1:Nstates_exposure){
	          W[,,z]  <- transitions_pop[w,x,,,(y==6)+1,(z==breeding_month)+1,i]*transitions_disease[y,z]
	        }

	        for (t2 in 1:12){
	          Q[w,x,y,t2,i] <- utility[w,x,y,Tmonths[t],i]
	        } 
	        Q[w,x,y,Tmonths[t],i] <- utility[w,x,y,Tmonths[t],i] + sum(discount*W[,,]*Vtplus[,,,Tmonths[t+1]])
	    }
	  }
	} 
	}
  
  Vt <- apply(Q, c(1,2,3,4), max)
  Vtplus <- Vt
  print(t)
  if (t <= 12){
    for (w in 1:Nstates_nWild){
      for (x in 1:Nstates_nCaptive){
        for (y in 1:Nstates_exposure){
            D[w,x,y,Tmonths[t]] <- max(actions[(which(Q[w,x,y,Tmonths[t],] == Vt[w,x,y,Tmonths[t]]))][which(abs(actions[(which(Q[w,x,y,Tmonths[t],] == Vt[w,x,y,Tmonths[t]]))])==min(abs(actions[(which(Q[w,x,y,Tmonths[t],] == Vt[w,x,y,Tmonths[t]]))])))])
            if(Vt[w,x,y,Tmonths[t]]==0){
              D[w,x,y,Tmonths[t]] <- NA
            }
        }
      }
    }
  }
}


```

```{r plot result}
state_space <- expand.grid(Nw = 1:21,
                           Nc = 1:21,
                           Exposure = 1:6) |>
  mutate(Action = NA)

for (i in 1:nrow(state_space)){
  state_space$Action[i] <- D[state_space$Nw[i],
                          state_space$Nc[i],
                          state_space$Exposure[i],
                          7]
}
           

state_space |>
  ggplot(aes(x = Nc, y = Nw, fill = Action)) +
  geom_tile() + 
  facet_wrap(vars(Exposure)) +
  scale_fill_scico(palette = 'vik', midpoint = 0)
```
